### PR TITLE
check contentType is defined before calling indexOf

### PR DESCRIPTION
**Pull request by sc0ttyd**
Fixes bug when used in conjunction with koa-bodyparser.

### CODE REVIEW

**Comment by sc0ttyd** [comment]
Could you please merge this, as it is causing issues for me. Thanks

**Comment by popomore** [comment]
I'll release later.

**Comment by sc0ttyd** [comment]
Thanks @popomore :+1: :smile:

**Comment by popomore** [comment]
+ koa-proxy@0.4.1

**Pull request merged**
